apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  strategy:
    type: {{ .Values.mysql.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - image: {{ .Values.mysql.container.image.name }}
          name: {{ .Values.mysql.name }}
          env:
            - name: MYSQL_DATABASE
              value: employees
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
          ports:
            - containerPort: {{ .Values.mysql.container.port }}
              name: mysql
